---
- name: Install kubernetes dependencies
  hosts: all
  become: true
  vars_files:
    - vars/config.yml
  tasks:
    - name: Check if swap is enabled
      ansible.builtin.command: swapon --show
      register: swapon_mounts
      changed_when: swapon_mounts.rc != 0

    - name: Disable swap
      when: swapon_mounts.stdout | length > 0
      block:
        - name: Disable swap
          ansible.builtin.command: swapoff -a
          changed_when: true

        - name: Comment out swap entry in fstab
          ansible.builtin.replace:
            path: /etc/fstab
            regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
            replace: '#\1\2\3swap\4'
            backup: true

    - name: Install kublet, kubeadm and kubeclt
      ansible.builtin.apt:
        pkg:
          - kubelet={{ kubernetes_version }}
          - kubeadm={{ kubernetes_version }}
          - kubectl={{ kubernetes_version }}

    #  Updating kubernetes should NOT be done automatically with system updates
    - name: Mark kubernetes and containerd dependencies to hold
      ansible.builtin.dpkg_selections:
        name: "{{ item }}"
        selection: hold
      with_items:
        - kubelet
        - kubeadm
        - kubectl

    - name: Start kublet service
      ansible.builtin.systemd:
        name: kubelet.service
        enabled: true
        state: started

    # https://kubernetes.io/docs/setup/production-environment/container-runtimes/
    - name: Configure containerd
      block:
        - name: Add OverlayFS module to kernel
          ansible.builtin.command: modprobe overlay
          register: mp_overlay
          changed_when: mp_overlay.rc != 0

        - name: Add bridge netfilter module to kernel
          ansible.builtin.command: modprobe br_netfilter
          register: mp_br_netfilter
          changed_when: mp_br_netfilter.rc != 0

        - name: Persist kernel modules between restarts
          ansible.builtin.template:
            src: templates/modules_load_k8s.conf
            dest: /etc/modules-load.d/k8s.conf
            owner: root
            group: root
            mode: "0600"

        - name: Persist sysctl params across reboots
          ansible.builtin.template:
            src: templates/sysctl_k8s.conf
            dest: /etc/sysctl.d/k8s.conf
            owner: root
            group: root
            mode: "0600"
          notify: Reload sysctl

        - name: Install containerd
          ansible.builtin.apt:
            name: containerd.io
            state: present

        - name: Mark containerd package on hold
          ansible.builtin.dpkg_selections:
            name: containerd.io
            selection: hold

        # Default configuration generated with
        # "containerd config default"
        # Modified the "SystemdCgroup" to true as ubuntu is using systemd
        # And registry.k8s.io/pause:3.6 to 3.9 to match up with kubeadm
        - name: Copy contaienrd configuration
          ansible.builtin.copy:
            src: templates/containerd_conf.toml
            dest: /etc/containerd/config.toml
            owner: root
            group: root
            mode: "0644"
          notify: Restart containerd

        - name: Enable containerd service
          ansible.builtin.systemd:
            name: containerd
            enabled: true
          notify: Restart containerd

  handlers:
    - name: Restart containerd
      ansible.builtin.systemd:
        name: containerd
        state: restarted

    - name: Reload sysctl
      ansible.builtin.command: sysctl --system
      register: sysctl_reload
      changed_when: sysctl_reload.rc != 0
