---
- name: Bootstrap control plain
  hosts: cpn
  become: true
  vars_files:
    - vars/config.yml

  tasks:
    - name: Set public interface & IP fact
      ansible.builtin.set_fact:
        public_interface: "{{ hostvars[inventory_hostname]['ansible_' + item].device }}"
        cpn_public_ip: "{{ hostvars[inventory_hostname]['ansible_' + item].ipv4.address }}"
      when:
        - hostvars[inventory_hostname]['ansible_' + item].ipv4 is defined
        - hostvars[inventory_hostname]['ansible_' + item].ipv4.address | ansible.utils.ipaddr( cluster.public_subnet )
      with_items: "{{ ansible_interfaces }}"

    - name: Copy flannel configuration
      ansible.builtin.template:
        src: templates/flannel.yml.j2
        dest: /etc/kubernetes/flannel.yml
        owner: root
        group: root
        mode: "0600"

    - name: Copy cluster configuration
      ansible.builtin.template:
        src: templates/kubeadm-init.yml.j2
        dest: /etc/kubernetes/kubeadminit.yml
        owner: root
        group: root
        mode: "0600"

    - name: Check cluster status
      ansible.builtin.command: kubectl get nodes
      register: cluster_exists
      ignore_errors: true
      failed_when: false
      changed_when: false

    - name: Initialise cluster
      when: cluster_exists.rc == 1
      block:
        - name: Kubeadm initialise control plain
          ansible.builtin.shell: kubeadm init --config /etc/kubernetes/kubeadminit.yml > /etc/kubernetes/kubeinit.log
          changed_when: false

        - name: Create ~/.kube directory
          ansible.builtin.file:
            name: /root/.kube
            state: directory
            owner: root
            group: root
            mode: "1700"

        - name: Copy .kube/config file
          ansible.builtin.copy:
            src: /etc/kubernetes/admin.conf
            dest: /root/.kube/config
            owner: root
            group: root
            mode: "0700"
            remote_src: true

        - name: Create flannel container
          ansible.builtin.command: kubectl apply -f /etc/kubernetes/flannel.yml
          changed_when: false

        - name: Wait for flannel to start up
          ansible.builtin.wait_for:
            path: /etc/cni/net.d/10-flannel.conflist
            timeout: 120

    # Maybe use wait_for instead?
    - name: Wait for control plain to be ready
      ansible.builtin.shell: kubectl get pods -A | grep -v -iE 'running|namespace' || true
      register: pods_running
      until: pods_running.stdout == ''
      retries: 12
      delay: 10
      changed_when: pods_running.rc != 0
      tags:
        - skip_ansible_lint
