---
- name: Prepare ubuntu system
  hosts: n1
  become: true 
  tasks: 
    - name: disable ufw
      ansible.builtin.systemd:
        name: ufw 
        state: stopped 
        enabled: no
      when: disable_firewall