--- 
disable_firewall: yes
kubernetes_version: 1.27.3
kubernetes_version_apt: 1.27.3-00
containerd_version_apt: 1.6.21-1
cluster: 
  control_plain_ip: 192.168.56.10
  kubernetes_ip_range: 10.96.0.0/12
  calico_ip_range: 10.111.0.0/16 # needs to fall under kubernetes range
